site_name: CFPA Music Technology Handbook (2024-2025)

theme:
  name: material

nav:
  - Home: index.md
  - Calendar: calendar.md
  - Program Requirements: program-requirements.md
  - Course Outline: course-outline.md
  - Expectations: expectations.md
  - Communication: communication.md
  - Auditions: auditions.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css
